In [1]:
import yfinance as yf

aapl= yf.Ticker("aapl")
aapl

yfinance.Ticker object <AAPL>

In [2]:
#To get the historical data we want to use the history() method, which is the most “complicated” method in the yfinance library.

#It takes the following parameters as input:

#period: data period to download (either use period parameter or use start and end) Valid periods are:
#“1d”, “5d”, “1mo”, “3mo”, “6mo”, “1y”, “2y”, “5y”, “10y”, “ytd”, “max”
#interval: data interval (1m data is only for available for last 7 days, and data interval <1d for the last 60 days) Valid intervals are:
#“1m”, “2m”, “5m”, “15m”, “30m”, “60m”, “90m”, “1h”, “1d”, “5d”, “1wk”, “1mo”, “3mo”
#start: If not using period – in the format (yyyy-mm-dd) or datetime.
#end: If not using period – in the format (yyyy-mm-dd) or datetime.
#prepost: Include Pre and Post regular market data in results? (Default is False)- no need usually to change this from False
#auto_adjust: Adjust all OHLC (Open/High/Low/Close prices) automatically? (Default is True)- just leave this always as true and don’t worry about it
#actions: Download stock dividends and stock splits events? (Default is True)

In [4]:
aapl_historical = aapl.history(start="2023-11-02", end="2023-11-07", interval="1m")
aapl_historical

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2023-11-02 09:30:00-04:00,175.520004,175.869995,175.460007,175.615005,2055724,0.0,0.0
2023-11-02 09:31:00-04:00,175.589996,176.100006,175.589996,176.054993,490493,0.0,0.0
2023-11-02 09:32:00-04:00,176.050003,176.270004,175.820007,176.044601,400010,0.0,0.0
2023-11-02 09:33:00-04:00,176.044998,176.239502,175.909195,176.104996,202581,0.0,0.0
2023-11-02 09:34:00-04:00,176.104996,176.164200,175.800003,175.940002,177160,0.0,0.0
...,...,...,...,...,...,...,...
2023-11-06 15:55:00-05:00,178.820007,179.050003,178.809998,178.960007,362542,0.0,0.0
2023-11-06 15:56:00-05:00,178.960007,179.089996,178.945007,179.081802,255602,0.0,0.0
2023-11-06 15:57:00-05:00,179.080002,179.139999,179.059998,179.110001,291654,0.0,0.0
2023-11-06 15:58:00-05:00,179.119995,179.220001,179.110001,179.195007,576719,0.0,0.0
2023-11-06 15:59:00-05:00,179.199997,179.330002,179.179993,179.289993,1404977,0.0,0.0

In [5]:
#To download the historical data for multiple tickers at once you can use the download module.

#It takes mostly the same arguments as the history() method on a ticker object, but additionally:

#group_by: group by column or ticker (‘column’/’ticker’, default is ‘column’)
#threads: use threads for mass downloading? (True/False/Integer)
#proxy: proxy URL if you want to use a proxy server for downloading the data (optional, default is None)

In [6]:
data = yf.download("AMZN AAPL GOOG", start="2017-01-01", end="2017-04-30")
data

[*********************100%%**********************]  3 of 3 completed

            Adj Close                            Close                        \
                 AAPL       AMZN       GOOG       AAPL       AMZN       GOOG
Date
2017-01-03  27.059307  37.683498  39.306999  29.037500  37.683498  39.306999
2017-01-04  27.029016  37.859001  39.345001  29.004999  37.859001  39.345001
2017-01-05  27.166471  39.022499  39.701000  29.152500  39.022499  39.701000
2017-01-06  27.469330  39.799500  40.307499  29.477501  39.799500  40.307499
2017-01-09  27.720938  39.846001  40.332500  29.747499  39.846001  40.332500
...               ...        ...        ...        ...        ...        ...
2017-04-24  33.608711  45.370499  43.138000  35.910000  45.370499  43.138000
2017-04-25  33.816944  45.381001  43.615002  36.132500  45.381001  43.615002
2017-04-26  33.618061  45.464500  43.586498  35.919998  45.464500  43.586498
2017-04-27  33.643795  45.918999  43.712502  35.947498  45.918999  43.712502
2017-04-28  33.611038  46.249500  45.298000  35.912498  46.249500  45.298000

                 High                              Low                        \
                 AAPL       AMZN       GOOG       AAPL       AMZN       GOOG
Date
2017-01-03  29.082500  37.938000  39.481499  28.690001  37.384998  38.790001
2017-01-04  29.127501  37.984001  39.567001  28.937500  37.709999  39.158001
2017-01-05  29.215000  39.119999  39.723999  28.952499  38.013000  39.250999
2017-01-06  29.540001  39.972000  40.395000  29.117500  38.924000  39.610199
2017-01-09  29.857500  40.088501  40.498299  29.485001  39.588501  40.141499
...               ...        ...        ...        ...        ...        ...
2017-04-24  35.987499  45.499500  43.172501  35.794998  45.191002  42.493000
2017-04-25  36.224998  45.473999  43.750000  35.967499  45.150002  43.140499
2017-04-26  36.150002  45.787498  43.802502  35.845001  45.377998  43.387402
2017-04-27  36.040001  46.092999  43.770000  35.827499  45.605499  43.519001
2017-04-28  36.075001  47.479500  45.842499  35.817501  46.216499  45.288502

                 Open                           Volume
                 AAPL       AMZN       GOOG       AAPL       AMZN      GOOG
Date
2017-01-03  28.950001  37.896000  38.940498  115127600   70422000  33146000
2017-01-04  28.962500  37.919498  39.417999   84472400   50210000  21460000
2017-01-05  28.980000  38.077499  39.304001   88774400  116602000  26704000
2017-01-06  29.195000  39.118000  39.763000  127007600  119724000  32804000
2017-01-09  29.487499  39.900002  40.320000  134247600   68922000  25492000
...               ...        ...        ...        ...        ...       ...
2017-04-24  35.875000  45.433998  42.560001   68537200   62458000  27450000
2017-04-25  35.977501  45.352001  43.250000   75486000   67612000  33440000
2017-04-26  36.117500  45.514999  43.711498   80164800   52178000  24744000
2017-04-27  35.980000  45.719501  43.680000   56985200  106110000  40536000
2017-04-28  36.022499  47.441502  45.533001   83441600  147294000  65526000

[81 rows x 18 columns]

In [7]:
data = yf.download("AMZN AAPL GOOG", start="2017-01-01",
                    end="2017-04-30", group_by='tickers')
data

[*********************100%%**********************]  3 of 3 completed

                 GOOG                                                        \
                 Open       High        Low      Close  Adj Close    Volume
Date
2017-01-03  38.940498  39.481499  38.790001  39.306999  39.306999  33146000
2017-01-04  39.417999  39.567001  39.158001  39.345001  39.345001  21460000
2017-01-05  39.304001  39.723999  39.250999  39.701000  39.701000  26704000
2017-01-06  39.763000  40.395000  39.610199  40.307499  40.307499  32804000
2017-01-09  40.320000  40.498299  40.141499  40.332500  40.332500  25492000
...               ...        ...        ...        ...        ...       ...
2017-04-24  42.560001  43.172501  42.493000  43.138000  43.138000  27450000
2017-04-25  43.250000  43.750000  43.140499  43.615002  43.615002  33440000
2017-04-26  43.711498  43.802502  43.387402  43.586498  43.586498  24744000
2017-04-27  43.680000  43.770000  43.519001  43.712502  43.712502  40536000
2017-04-28  45.533001  45.842499  45.288502  45.298000  45.298000  65526000

                 AAPL                                                         \
                 Open       High        Low      Close  Adj Close     Volume
Date
2017-01-03  28.950001  29.082500  28.690001  29.037500  27.059307  115127600
2017-01-04  28.962500  29.127501  28.937500  29.004999  27.029020   84472400
2017-01-05  28.980000  29.215000  28.952499  29.152500  27.166475   88774400
2017-01-06  29.195000  29.540001  29.117500  29.477501  27.469330  127007600
2017-01-09  29.487499  29.857500  29.485001  29.747499  27.720936  134247600
...               ...        ...        ...        ...        ...        ...
2017-04-24  35.875000  35.987499  35.794998  35.910000  33.608707   68537200
2017-04-25  35.977501  36.224998  35.967499  36.132500  33.816940   75486000
2017-04-26  36.117500  36.150002  35.845001  35.919998  33.618061   80164800
2017-04-27  35.980000  36.040001  35.827499  35.947498  33.643803   56985200
2017-04-28  36.022499  36.075001  35.817501  35.912498  33.611038   83441600

                 AMZN
                 Open       High        Low      Close  Adj Close     Volume
Date
2017-01-03  37.896000  37.938000  37.384998  37.683498  37.683498   70422000
2017-01-04  37.919498  37.984001  37.709999  37.859001  37.859001   50210000
2017-01-05  38.077499  39.119999  38.013000  39.022499  39.022499  116602000
2017-01-06  39.118000  39.972000  38.924000  39.799500  39.799500  119724000
2017-01-09  39.900002  40.088501  39.588501  39.846001  39.846001   68922000
...               ...        ...        ...        ...        ...        ...
2017-04-24  45.433998  45.499500  45.191002  45.370499  45.370499   62458000
2017-04-25  45.352001  45.473999  45.150002  45.381001  45.381001   67612000
2017-04-26  45.514999  45.787498  45.377998  45.464500  45.464500   52178000
2017-04-27  45.719501  46.092999  45.605499  45.918999  45.918999  106110000
2017-04-28  47.441502  47.479500  46.216499  46.249500  46.249500  147294000

[81 rows x 18 columns]

In [13]:
aapl = yf.Ticker("aapl")
aapl.dividends

Date
1987-05-11 00:00:00-04:00    0.000536
1987-08-10 00:00:00-04:00    0.000536
1987-11-17 00:00:00-05:00    0.000714
1988-02-12 00:00:00-05:00    0.000714
1988-05-16 00:00:00-04:00    0.000714
                               ...
2022-08-05 00:00:00-04:00    0.230000
2022-11-04 00:00:00-04:00    0.230000
2023-02-10 00:00:00-05:00    0.230000
2023-05-12 00:00:00-04:00    0.240000
2023-08-11 00:00:00-04:00    0.240000
Name: Dividends, Length: 80, dtype: float64

In [24]:
#To download options data we can use the option_chain() method. It takes the parameter as input:

#date: (YYYY-MM-DD), expiry date. If None return all options data.
#And has the opt.calls and opt.puts methods

In [25]:
aapl.options

('2023-11-10',
 '2023-11-17',
 '2023-11-24',
 '2023-12-01',
 '2023-12-08',
 '2023-12-15',
 '2023-12-22',
 '2024-01-19',
 '2024-02-16',
 '2024-03-15',
 '2024-04-19',
 '2024-06-21',
 '2024-09-20',
 '2024-12-20',
 '2025-01-17',
 '2025-06-20',
 '2025-09-19',
 '2025-12-19',
 '2026-01-16')

In [27]:
# get option chain calls data for specific expiration date
opt = aapl.option_chain(date='2023-11-10')
opt.calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL231110C00050000,2023-11-07 17:15:35+00:00,50.0,130.70,131.70,132.10,8.799995,7.219029,2.0,11,4.828129,True,REGULAR,USD
1,AAPL231110C00060000,2023-10-26 14:01:29+00:00,60.0,109.94,121.75,122.10,0.000000,0.000000,1.0,0,4.304692,True,REGULAR,USD
2,AAPL231110C00090000,2023-11-06 14:37:31+00:00,90.0,88.10,91.75,92.10,0.000000,0.000000,3.0,6,2.812503,True,REGULAR,USD
3,AAPL231110C00100000,2023-11-02 18:57:26+00:00,100.0,77.47,81.70,82.10,0.000000,0.000000,7.0,11,2.343754,True,REGULAR,USD
4,AAPL231110C00105000,2023-10-30 17:29:00+00:00,105.0,65.10,76.70,77.10,0.000000,0.000000,1.0,4,2.167973,True,REGULAR,USD
5,AAPL231110C00110000,2023-11-03 17:36:16+00:00,110.0,65.50,71.75,72.10,0.000000,0.000000,80.0,19,2.070317,True,REGULAR,USD
6,AAPL231110C00115000,2023-10-13 18:35:44+00:00,115.0,64.80,66.75,67.10,0.000000,0.000000,3.0,34,1.902344,True,REGULAR,USD
7,AAPL231110C00120000,2023-10-16 14:21:32+00:00,120.0,58.55,61.75,62.10,0.000000,0.000000,2.0,13,1.742189,True,REGULAR,USD
8,AAPL231110C00125000,2023-11-03 18:38:04+00:00,125.0,50.90,56.75,57.10,0.000000,0.000000,2.0,44,1.589846,True,REGULAR,USD
9,AAPL231110C00130000,2023-11-06 17:52:30+00:00,130.0,48.81,51.75,52.15,0.000000,0.000000,2.0,13,1.484378,True,REGULAR,USD
10,AAPL231110C00135000,2023-11-06 16:19:18+00:00,135.0,44.36,46.75,47.10,0.000000,0.000000,4.0,268,1.296879,True,REGULAR,USD
11,AAPL231110C00140000,2023-11-07 16:28:57+00:00,140.0,41.56,41.75,42.15,2.670002,6.865523,9.0,685,1.191410,True,REGULAR,USD
12,AAPL231110C00144000,2023-11-03 14:49:34+00:00,144.0,31.92,37.75,38.10,0.000000,0.000000,1.0,11,1.044927,True,REGULAR,USD
13,AAPL231110C00145000,2023-11-07 15:07:12+00:00,145.0,35.61,36.80,37.15,1.690002,4.982319,1.0,176,1.080083,True,REGULAR,USD
14,AAPL231110C00146000,2023-10-31 15:59:05+00:00,146.0,24.05,35.75,36.15,0.000000,0.000000,25.0,13,1.023442,True,REGULAR,USD
15,AAPL231110C00147000,2023-11-06 15:41:03+00:00,147.0,31.86,34.75,35.10,0.000000,0.000000,12.0,14,0.964844,True,REGULAR,USD
16,AAPL231110C00148000,2023-11-06 17:52:24+00:00,148.0,30.80,33.75,34.10,0.000000,0.000000,12.0,19,0.937501,True,REGULAR,USD
17,AAPL231110C00149000,2023-10-31 18:13:49+00:00,149.0,21.73,32.75,33.15,0.000000,0.000000,NaN,1,0.941407,True,REGULAR,USD
18,AAPL231110C00150000,2023-11-07 20:42:08+00:00,150.0,32.40,31.75,32.15,3.450001,11.917101,23.0,287,0.914063,True,REGULAR,USD
19,AAPL231110C00152500,2023-11-06 15:06:25+00:00,152.5,25.85,29.25,29.60,0.000000,0.000000,2.0,26,0.818361,True,REGULAR,USD
20,AAPL231110C00155000,2023-11-07 20:53:30+00:00,155.0,26.97,26.75,27.10,2.539999,10.397048,38.0,960,0.751956,True,REGULAR,USD
21,AAPL231110C00157500,2023-11-03 19:07:20+00:00,157.5,19.08,24.30,24.65,0.000000,0.000000,18.0,62,0.733401,True,REGULAR,USD
22,AAPL231110C00160000,2023-11-07 16:12:52+00:00,160.0,21.30,21.80,22.15,2.299999,12.105259,36.0,2391,0.665042,True,REGULAR,USD
23,AAPL231110C00162500,2023-11-07 18:53:20+00:00,162.5,19.86,19.35,19.65,3.110001,18.567167,7.0,477,0.614262,True,REGULAR,USD
24,AAPL231110C00165000,2023-11-07 19:44:05+00:00,165.0,17.27,16.80,17.15,3.120001,22.049477,81.0,2872,0.529302,True,REGULAR,USD
25,AAPL231110C00167500,2023-11-07 20:58:03+00:00,167.5,14.50,14.30,14.60,2.710000,22.985582,196.0,1989,0.522466,True,REGULAR,USD
26,AAPL231110C00170000,2023-11-07 20:59:28+00:00,170.0,11.90,11.85,12.15,2.349999,24.607323,618.0,7777,0.465826,True,REGULAR,USD
27,AAPL231110C00172500,2023-11-07 20:48:21+00:00,172.5,9.56,9.30,9.70,2.610001,37.553967,1256.0,6417,0.402838,True,REGULAR,USD
28,AAPL231110C00175000,2023-11-07 20:59:44+00:00,175.0,7.05,6.95,7.15,2.300000,48.421060,3913.0,14465,0.307624,True,REGULAR,USD
29,AAPL231110C00177500,2023-11-07 20:59:50+00:00,177.5,4.57,4.55,4.70,1.790000,64.388500,11024.0,25278,0.233894,True,REGULAR,USD
30,AAPL231110C00180000,2023-11-07 20:59:59+00:00,180.0,2.52,2.48,2.57,1.290000,104.878044,65536.0,35816,0.196785,True,REGULAR,USD
31,AAPL231110C00182500,2023-11-07 20:59:59+00:00,182.5,0.97,0.97,0.99,0.560000,136.585370,94621.0,32168,0.171151,False,REGULAR,USD
32,AAPL231110C00185000,2023-11-07 20:59:52+00:00,185.0,0.26,0.25,0.27,0.140000,116.666664,41601.0,24459,0.166512,False,REGULAR,USD
33,AAPL231110C00187500,2023-11-07 20:59:46+00:00,187.5,0.06,0.06,0.07,0.020000,50.000000,14491.0,11289,0.177743,False,REGULAR,USD
34,AAPL231110C00190000,2023-11-07 20:59:42+00:00,190.0,0.03,0.02,0.03,0.010000,50.000000,12630.0,15317,0.205086,False,REGULAR,USD
35,AAPL231110C00192500,2023-11-07 20:45:53+00:00,192.5,0.02,0.01,0.02,0.000000,0.000000,1243.0,4628,0.242195,False,REGULAR,USD
36,AAPL231110C00195000,2023-11-07 20:56:18+00:00,195.0,0.01,0.01,0.02,0.000000,0.000000,1503.0,17401,0.289070,False,REGULAR,USD
37,AAPL231110C00197500,2023-11-07 20:47:28+00:00,197.5,0.01,0.00,0.01,0.000000,0.000000,94.0,675,0.304694,False,REGULAR,USD
38,AAPL231110C00200000,2023-11-07 19:32:32+00:00,200.0,0.01,0.00,0.01,0.000000,0.000000,51.0,6497,0.351569,False,REGULAR,USD
39,AAPL231110C00202500,2023-11-03 13:34:49+00:00,202.5,0.01,0.00,0.01,0.000000,0.000000,52.0,370,0.390631,False,REGULAR,USD
40,AAPL231110C00205000,2023-11-07 16:18:46+00:00,205.0,0.01,0.00,0.01,0.000000,0.000000,197.0,1520,0.429693,False,REGULAR,USD
41,AAPL231110C00207500,2023-11-07 18:27:57+00:00,207.5,0.01,0.00,0.01,0.000000,0.000000,51.0,243,0.468755,False,REGULAR,USD
42,AAPL231110C00210000,2023-11-07 14:55:59+00:00,210.0,0.01,0.00,0.01,0.000000,0.000000,5.0,308,0.500005,False,REGULAR,USD
43,AAPL231110C00212500,2023-11-02 19:45:38+00:00,212.5,0.01,0.00,0.01,0.000000,0.000000,NaN,348,0.500005,False,REGULAR,USD
44,AAPL231110C00215000,2023-11-02 19:58:31+00:00,215.0,0.01,0.00,0.01,0.000000,0.000000,111.0,171,0.546880,False,REGULAR,USD
45,AAPL231110C00217500,2023-11-03 13:31:02+00:00,217.5,0.01,0.00,0.01,0.000000,0.000000,2.0,3,0.578129,False,REGULAR,USD
46,AAPL231110C00220000,2023-10-20 13:54:54+00:00,220.0,0.02,0.00,0.01,0.000000,0.000000,1.0,57,0.609379,False,REGULAR,USD
47,AAPL231110C00222500,2023-10-24 13:45:33+00:00,222.5,0.01,0.00,0.01,0.000000,0.000000,NaN,1,0.640629,False,REGULAR,USD
48,AAPL231110C00225000,2023-10-09 15:10:13+00:00,225.0,0.03,0.00,0.01,0.000000,0.000000,1.0,22,0.671878,False,REGULAR,USD
49,AAPL231110C00230000,2023-10-09 15:32:09+00:00,230.0,0.01,0.00,0.01,0.000000,0.000000,1.0,1,0.734378,False,REGULAR,USD
50,AAPL231110C00235000,2023-10-19 14:02:58+00:00,235.0,0.01,0.00,0.01,0.000000,0.000000,1.0,11,0.796877,False,REGULAR,USD
51,AAPL231110C00240000,2023-11-03 13:44:11+00:00,240.0,0.01,0.00,0.01,0.000000,0.000000,1.0,1,0.843752,False,REGULAR,USD
52,AAPL231110C00250000,2023-10-02 17:50:10+00:00,250.0,0.02,0.00,0.01,0.000000,0.000000,NaN,5,0.968750,False,REGULAR,USD
53,AAPL231110C00255000,2023-10-20 13:30:15+00:00,255.0,0.01,0.00,0.01,0.000000,0.000000,1.0,1,1.031255,False,REGULAR,USD
54,AAPL231110C00265000,2023-11-07 16:35:55+00:00,265.0,0.01,0.00,0.01,0.000000,0.000000,6.0,19,1.125004,False,REGULAR,USD

In [28]:
opt.puts

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL231110P00050000,2023-11-06 17:30:05+00:00,50.0,0.01,0.00,0.01,0.000000,0.000000,10.0,11,3.750001,False,REGULAR,USD
1,AAPL231110P00080000,2023-10-02 16:00:59+00:00,80.0,0.02,0.00,0.01,0.000000,0.000000,NaN,1,2.437504,False,REGULAR,USD
2,AAPL231110P00095000,2023-10-13 18:32:20+00:00,95.0,0.02,0.00,0.01,0.000000,0.000000,1.0,3,1.937500,False,REGULAR,USD
3,AAPL231110P00100000,2023-11-07 18:58:12+00:00,100.0,0.01,0.00,0.01,0.000000,0.000000,1.0,24,1.812501,False,REGULAR,USD
4,AAPL231110P00105000,2023-10-30 15:27:32+00:00,105.0,0.01,0.00,0.01,0.000000,0.000000,1.0,33,1.656252,False,REGULAR,USD
5,AAPL231110P00110000,2023-11-03 15:25:38+00:00,110.0,0.01,0.00,0.01,0.000000,0.000000,2.0,106,1.500002,False,REGULAR,USD
6,AAPL231110P00115000,2023-11-02 18:24:44+00:00,115.0,0.01,0.00,0.01,0.000000,0.000000,1.0,775,1.375003,False,REGULAR,USD
7,AAPL231110P00120000,2023-11-03 19:36:44+00:00,120.0,0.01,0.00,0.01,0.000000,0.000000,7.0,2238,1.281254,False,REGULAR,USD
8,AAPL231110P00125000,2023-11-06 20:51:28+00:00,125.0,0.01,0.00,0.01,0.000000,0.000000,13.0,435,1.156254,False,REGULAR,USD
9,AAPL231110P00130000,2023-11-06 14:30:00+00:00,130.0,0.01,0.00,0.01,0.000000,0.000000,50.0,335,1.031255,False,REGULAR,USD
10,AAPL231110P00135000,2023-11-07 19:32:41+00:00,135.0,0.01,0.00,0.00,0.000000,0.000000,25.0,886,0.500005,False,REGULAR,USD
11,AAPL231110P00138000,2023-11-07 14:53:19+00:00,138.0,0.01,0.00,0.00,0.000000,0.000000,250.0,1485,0.500005,False,REGULAR,USD
12,AAPL231110P00139000,2023-11-06 14:30:09+00:00,139.0,0.01,0.00,0.01,0.000000,0.000000,178.0,843,0.843752,False,REGULAR,USD
13,AAPL231110P00140000,2023-11-07 20:54:12+00:00,140.0,0.01,0.00,0.01,0.000000,0.000000,5529.0,2444,0.828127,False,REGULAR,USD
14,AAPL231110P00141000,2023-11-03 19:55:56+00:00,141.0,0.02,0.00,0.02,0.000000,0.000000,122.0,100,0.859376,False,REGULAR,USD
15,AAPL231110P00142000,2023-11-07 20:58:54+00:00,142.0,0.01,0.00,0.02,0.000000,0.000000,1856.0,138,0.843752,False,REGULAR,USD
16,AAPL231110P00143000,2023-11-06 14:38:58+00:00,143.0,0.01,0.00,0.01,0.000000,0.000000,4.0,33,0.765627,False,REGULAR,USD
17,AAPL231110P00144000,2023-11-07 20:58:28+00:00,144.0,0.01,0.00,0.02,0.000000,0.000000,3030.0,922,0.796877,False,REGULAR,USD
18,AAPL231110P00145000,2023-11-07 20:58:32+00:00,145.0,0.01,0.00,0.02,0.000000,0.000000,2233.0,2647,0.765627,False,REGULAR,USD
19,AAPL231110P00146000,2023-11-07 20:57:16+00:00,146.0,0.01,0.01,0.02,0.000000,0.000000,873.0,1245,0.781252,False,REGULAR,USD
20,AAPL231110P00147000,2023-11-07 20:57:03+00:00,147.0,0.01,0.01,0.02,0.000000,0.000000,317.0,641,0.757815,False,REGULAR,USD
21,AAPL231110P00148000,2023-11-07 20:55:34+00:00,148.0,0.01,0.01,0.02,-0.010000,-50.000000,277.0,1681,0.734378,False,REGULAR,USD
22,AAPL231110P00149000,2023-11-07 20:52:31+00:00,149.0,0.01,0.01,0.02,0.000000,0.000000,660.0,664,0.718753,False,REGULAR,USD
23,AAPL231110P00150000,2023-11-07 20:55:29+00:00,150.0,0.01,0.01,0.02,0.000000,0.000000,314.0,6131,0.695316,False,REGULAR,USD
24,AAPL231110P00152500,2023-11-07 20:59:33+00:00,152.5,0.01,0.01,0.02,0.000000,0.000000,2326.0,1679,0.640629,False,REGULAR,USD
25,AAPL231110P00155000,2023-11-07 20:55:46+00:00,155.0,0.01,0.01,0.02,0.000000,0.000000,483.0,4106,0.585942,False,REGULAR,USD
26,AAPL231110P00157500,2023-11-07 20:59:37+00:00,157.5,0.02,0.01,0.03,-0.010000,-33.333336,330.0,4521,0.550786,False,REGULAR,USD
27,AAPL231110P00160000,2023-11-07 20:56:37+00:00,160.0,0.02,0.01,0.03,0.000000,0.000000,1414.0,10651,0.519536,False,REGULAR,USD
28,AAPL231110P00162500,2023-11-07 20:49:27+00:00,162.5,0.02,0.01,0.03,-0.020000,-50.000000,2259.0,10370,0.464849,False,REGULAR,USD
29,AAPL231110P00165000,2023-11-07 20:57:01+00:00,165.0,0.03,0.02,0.03,-0.010000,-25.000000,2526.0,13180,0.410162,False,REGULAR,USD
30,AAPL231110P00167500,2023-11-07 20:56:58+00:00,167.5,0.04,0.03,0.04,-0.020000,-33.333336,1786.0,14469,0.367194,False,REGULAR,USD
31,AAPL231110P00170000,2023-11-07 20:59:58+00:00,170.0,0.05,0.03,0.05,-0.060000,-54.545456,14456.0,36441,0.320319,False,REGULAR,USD
32,AAPL231110P00172500,2023-11-07 20:58:48+00:00,172.5,0.06,0.05,0.07,-0.150000,-71.428566,21239.0,24157,0.276374,False,REGULAR,USD
33,AAPL231110P00175000,2023-11-07 20:59:53+00:00,175.0,0.10,0.10,0.11,-0.360000,-78.260870,35197.0,31579,0.233406,False,REGULAR,USD
34,AAPL231110P00177500,2023-11-07 20:59:58+00:00,177.5,0.25,0.23,0.25,-0.710000,-73.958330,46483.0,15744,0.204110,False,REGULAR,USD
35,AAPL231110P00180000,2023-11-07 20:59:59+00:00,180.0,0.67,0.65,0.70,-1.330000,-66.500000,72202.0,7167,0.189217,False,REGULAR,USD
36,AAPL231110P00182500,2023-11-07 20:59:57+00:00,182.5,1.68,1.64,1.72,-2.020000,-54.594593,23564.0,2338,0.177743,True,REGULAR,USD
37,AAPL231110P00185000,2023-11-07 20:59:42+00:00,185.0,3.47,3.40,3.65,-2.430000,-41.186440,3627.0,5097,0.205574,True,REGULAR,USD
38,AAPL231110P00187500,2023-11-07 20:53:42+00:00,187.5,5.75,5.65,6.00,-2.750000,-32.352943,286.0,80,0.258796,True,REGULAR,USD
39,AAPL231110P00190000,2023-11-07 20:56:59+00:00,190.0,8.50,8.15,8.40,-2.750000,-24.444445,45.0,104,0.302253,True,REGULAR,USD
40,AAPL231110P00192500,2023-11-07 19:50:39+00:00,192.5,10.50,10.60,10.90,-3.300000,-23.913046,36.0,51,0.368170,True,REGULAR,USD
41,AAPL231110P00195000,2023-11-07 17:16:55+00:00,195.0,14.15,13.05,13.35,-2.700001,-16.023743,110.0,12,0.408209,True,REGULAR,USD
42,AAPL231110P00197500,2023-11-07 18:14:32+00:00,197.5,15.65,15.55,15.85,-3.610001,-18.743513,11.0,4,0.465826,True,REGULAR,USD
43,AAPL231110P00200000,2023-11-06 20:49:42+00:00,200.0,21.30,18.05,18.35,0.000000,0.000000,6.0,62,0.521489,True,REGULAR,USD
44,AAPL231110P00202500,2023-11-06 19:18:03+00:00,202.5,24.15,20.55,20.85,0.000000,0.000000,29.0,30,0.576176,True,REGULAR,USD
45,AAPL231110P00205000,2023-11-07 18:03:01+00:00,205.0,23.30,23.10,23.30,-2.700001,-10.384619,46.0,20,0.591801,True,REGULAR,USD
46,AAPL231110P00212500,2023-10-25 19:54:40+00:00,212.5,41.40,30.55,30.90,0.000000,0.000000,NaN,0,0.640629,True,REGULAR,USD
47,AAPL231110P00215000,2023-11-06 14:52:16+00:00,215.0,36.50,33.05,33.40,0.000000,0.000000,1.0,1,0.683597,True,REGULAR,USD
48,AAPL231110P00245000,2023-10-06 17:14:34+00:00,245.0,67.90,67.90,68.95,0.000000,0.000000,1.0,0,2.855960,True,REGULAR,USD

In [30]:
aapl.actions

                           Dividends  Stock Splits
Date
1987-05-11 00:00:00-04:00   0.000536           0.0
1987-06-16 00:00:00-04:00   0.000000           2.0
1987-08-10 00:00:00-04:00   0.000536           0.0
1987-11-17 00:00:00-05:00   0.000714           0.0
1988-02-12 00:00:00-05:00   0.000714           0.0
...                              ...           ...
2022-08-05 00:00:00-04:00   0.230000           0.0
2022-11-04 00:00:00-04:00   0.230000           0.0
2023-02-10 00:00:00-05:00   0.230000           0.0
2023-05-12 00:00:00-04:00   0.240000           0.0
2023-08-11 00:00:00-04:00   0.240000           0.0

[85 rows x 2 columns]

In [31]:
aapl.financials

,2023-09-30,2022-09-30,2021-09-30,2020-09-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0
Tax Rate For Calcs,0.147192,0.162045,0.133023,0.144282
Normalized EBITDA,125820000000.0,130541000000.0,120233000000.0,77344000000.0
Net Income From Continuing Operation Net Minority Interest,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Reconciled Depreciation,11519000000.0,11104000000.0,11284000000.0,11056000000.0
Reconciled Cost Of Revenue,214137000000.0,223546000000.0,212981000000.0,169559000000.0
EBITDA,125820000000.0,130541000000.0,120233000000.0,77344000000.0
EBIT,114301000000.0,119437000000.0,108949000000.0,66288000000.0
Net Interest Income,NaN,-106000000.0,198000000.0,890000000.0
Interest Expense,NaN,2931000000.0,2645000000.0,2873000000.0
Interest Income,NaN,2825000000.0,2843000000.0,3763000000.0
Normalized Income,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income From Continuing And Discontinued Operation,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Total Expenses,268984000000.0,274891000000.0,256868000000.0,208227000000.0
Total Operating Income As Reported,114301000000.0,119437000000.0,108949000000.0,66288000000.0
Diluted Average Shares,15812547000.0,16325819000.0,16864919000.0,17528214000.0
Basic Average Shares,15744231000.0,16215963000.0,16701272000.0,17352119000.0
Diluted EPS,6.13,6.11,5.61,3.28
Basic EPS,6.16,6.15,5.67,3.31
Diluted NI Availto Com Stockholders,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income Common Stockholders,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income Including Noncontrolling Interests,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income Continuous Operations,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Tax Provision,16741000000.0,19300000000.0,14527000000.0,9680000000.0
Pretax Income,113736000000.0,119103000000.0,109207000000.0,67091000000.0
Other Income Expense,-565000000.0,-334000000.0,258000000.0,803000000.0
Other Non Operating Income Expenses,-565000000.0,-334000000.0,258000000.0,803000000.0
Net Non Operating Interest Income Expense,NaN,-106000000.0,198000000.0,890000000.0
Interest Expense Non Operating,NaN,2931000000.0,2645000000.0,2873000000.0
Interest Income Non Operating,NaN,2825000000.0,2843000000.0,3763000000.0
Operating Income,114301000000.0,119437000000.0,108949000000.0,66288000000.0
Operating Expense,54847000000.0,51345000000.0,43887000000.0,38668000000.0
Research And Development,29915000000.0,26251000000.0,21914000000.0,18752000000.0
Selling General And Administration,24932000000.0,25094000000.0,21973000000.0,19916000000.0
Gross Profit,169148000000.0,170782000000.0,152836000000.0,104956000000.0
Cost Of Revenue,214137000000.0,223546000000.0,212981000000.0,169559000000.0
Total Revenue,383285000000.0,394328000000.0,365817000000.0,274515000000.0
Operating Revenue,383285000000.0,394328000000.0,365817000000.0,274515000000.0

In [32]:
aapl.quarterly_financials

,2023-09-30,2023-06-30,2023-03-31,2022-12-31,2022-09-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,0.0
Tax Rate For Calcs,0.149715,0.125456,0.148756,0.157904,0.15963
Normalized EBITDA,29622000000.0,26050000000.0,31216000000.0,38932000000.0,27759000000.0
Net Income From Continuing Operation Net Minority Interest,22956000000.0,19881000000.0,24160000000.0,29998000000.0,20721000000.0
Reconciled Depreciation,2653000000.0,3052000000.0,2898000000.0,2916000000.0,2865000000.0
Reconciled Cost Of Revenue,49071000000.0,45384000000.0,52860000000.0,66822000000.0,52051000000.0
EBITDA,29622000000.0,26050000000.0,31216000000.0,38932000000.0,27759000000.0
EBIT,26969000000.0,22998000000.0,28318000000.0,36016000000.0,24894000000.0
Net Interest Income,NaN,-18000000.0,-12000000.0,-135000000.0,-74000000.0
Interest Expense,NaN,998000000.0,930000000.0,1003000000.0,827000000.0
Interest Income,NaN,980000000.0,918000000.0,868000000.0,753000000.0
Normalized Income,22956000000.0,19881000000.0,24160000000.0,29998000000.0,20721000000.0
Net Income From Continuing And Discontinued Operation,22956000000.0,19881000000.0,24160000000.0,29998000000.0,20721000000.0
Total Expenses,62529000000.0,58799000000.0,66518000000.0,81138000000.0,65252000000.0
Total Operating Income As Reported,26969000000.0,22998000000.0,28318000000.0,36016000000.0,24894000000.0
Diluted Average Shares,15672400000.0,15775021000.0,15847050000.0,15955718000.0,16118465000.0
Basic Average Shares,15599434000.0,15697614000.0,15787154000.0,15892723000.0,16030382000.0
Diluted EPS,1.46,1.26,1.52,1.88,1.29
Basic EPS,1.47,1.27,1.53,1.89,1.29
Diluted NI Availto Com Stockholders,22956000000.0,19881000000.0,24160000000.0,29998000000.0,20721000000.0
Net Income Common Stockholders,22956000000.0,19881000000.0,24160000000.0,29998000000.0,20721000000.0
Net Income,22956000000.0,19881000000.0,24160000000.0,29998000000.0,20721000000.0
Net Income Including Noncontrolling Interests,22956000000.0,19881000000.0,24160000000.0,29998000000.0,20721000000.0
Net Income Continuous Operations,22956000000.0,19881000000.0,24160000000.0,29998000000.0,20721000000.0
Tax Provision,4042000000.0,2852000000.0,4222000000.0,5625000000.0,3936000000.0
Pretax Income,26998000000.0,22733000000.0,28382000000.0,35623000000.0,24657000000.0
Other Income Expense,29000000.0,-265000000.0,64000000.0,-393000000.0,-237000000.0
Other Non Operating Income Expenses,29000000.0,-265000000.0,64000000.0,-393000000.0,-237000000.0
Net Non Operating Interest Income Expense,NaN,-18000000.0,-12000000.0,-135000000.0,-74000000.0
Interest Expense Non Operating,NaN,998000000.0,930000000.0,1003000000.0,827000000.0
Interest Income Non Operating,NaN,980000000.0,918000000.0,868000000.0,753000000.0
Operating Income,26969000000.0,22998000000.0,28318000000.0,36016000000.0,24894000000.0
Operating Expense,13458000000.0,13415000000.0,13658000000.0,14316000000.0,13201000000.0
Research And Development,7307000000.0,7442000000.0,7457000000.0,7709000000.0,6761000000.0
Selling General And Administration,6151000000.0,5973000000.0,6201000000.0,6607000000.0,6440000000.0
Gross Profit,40427000000.0,36413000000.0,41976000000.0,50332000000.0,38095000000.0
Cost Of Revenue,49071000000.0,45384000000.0,52860000000.0,66822000000.0,52051000000.0
Total Revenue,89498000000.0,81797000000.0,94836000000.0,117154000000.0,90146000000.0
Operating Revenue,89498000000.0,81797000000.0,94836000000.0,117154000000.0,90146000000.0

In [36]:
aapl.options

('2023-11-10',
 '2023-11-17',
 '2023-11-24',
 '2023-12-01',
 '2023-12-08',
 '2023-12-15',
 '2023-12-22',
 '2024-01-19',
 '2024-02-16',
 '2024-03-15',
 '2024-04-19',
 '2024-06-21',
 '2024-09-20',
 '2024-12-20',
 '2025-01-17',
 '2025-06-20',
 '2025-09-19',
 '2025-12-19',
 '2026-01-16')

In [37]:
date = aapl.options[1]

In [38]:
options = aapl.option_chain(date)

In [39]:
options.calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL231117C00050000,2023-10-26 16:42:16+00:00,50.0,116.44,131.70,132.15,0.00,0.000000,2.0,118,3.007815,True,REGULAR,USD
1,AAPL231117C00055000,2023-10-25 15:31:03+00:00,55.0,124.30,126.70,127.15,6.75,5.742238,20.0,82,2.789066,True,REGULAR,USD
2,AAPL231117C00060000,2023-10-26 16:24:19+00:00,60.0,106.10,121.65,122.15,0.00,0.000000,3.0,32,2.515629,True,REGULAR,USD
3,AAPL231117C00065000,2023-10-24 14:20:37+00:00,65.0,107.05,116.65,117.15,0.00,0.000000,17.0,67,2.343754,True,REGULAR,USD
4,AAPL231117C00070000,2023-10-24 14:15:08+00:00,70.0,102.10,111.70,112.15,0.00,0.000000,22.0,69,2.253911,True,REGULAR,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,AAPL231117C00275000,2023-10-03 17:24:36+00:00,275.0,0.01,0.00,0.01,0.00,0.000000,1.0,1289,0.750003,False,REGULAR,USD
64,AAPL231117C00280000,2023-09-28 15:04:17+00:00,280.0,0.01,0.00,0.01,0.00,0.000000,14.0,559,0.765627,False,REGULAR,USD
65,AAPL231117C00285000,2023-09-20 13:46:31+00:00,285.0,0.01,0.00,0.01,0.00,0.000000,25.0,306,0.796877,False,REGULAR,USD
66,AAPL231117C00290000,2023-09-28 15:09:04+00:00,290.0,0.01,0.00,0.01,0.00,0.000000,69.0,2635,0.828127,False,REGULAR,USD
67,AAPL231117C00300000,2023-11-06 14:30:03+00:00,300.0,0.01,0.00,0.01,0.00,0.000000,1.0,2298,0.875001,False,REGULAR,USD

In [40]:
options.calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   contractSymbol     68 non-null     object
 1   lastTradeDate      68 non-null     datetime64[ns, UTC]
 2   strike             68 non-null     float64
 3   lastPrice          68 non-null     float64
 4   bid                68 non-null     float64
 5   ask                68 non-null     float64
 6   change             68 non-null     float64
 7   percentChange      68 non-null     float64
 8   volume             65 non-null     float64
 9   openInterest       68 non-null     int64
 10  impliedVolatility  68 non-null     float64
 11  inTheMoney         68 non-null     bool
 12  contractSize       68 non-null     object
 13  currency           68 non-null     object
dtypes: bool(1), datetime64[ns, UTC](1), float64(8), int64(1), object(3)
memory usage: 7.1+ KB

In [42]:
import yfinance as yf

# Replace 'AAPL' with the desired stock ticker symbol
ticker = yf.Ticker('AAPL')

# Access options data
options_data = ticker.option_chain('2023-11-24').calls

# Filter options data by strike price
filtered_data = options_data[options_data['strike'] == 150]

print(filtered_data)

         contractSymbol             lastTradeDate  strike  lastPrice   bid  \
12  AAPL231124C00150000 2023-11-07 15:57:41+00:00   150.0      31.33  31.9

      ask  change  percentChange  volume  openInterest  impliedVolatility  \
12  32.35    1.93       6.564627     8.0            55           0.557622

    inTheMoney contractSize currency
12        True      REGULAR      USD